"""added has_dependent back to insured table as string


Revision ID: 007c8695b784
Revises: 454e9b9a2f52
Create Date: 2018-03-24 21:34:48.994896

"""

# revision identifiers, used by Alembic.
revision = '007c8695b784'
down_revision = '454e9b9a2f52'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insured', sa.Column('has_dependent', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insured', 'has_dependent')
    # ### end Alembic commands ###
