"""empty message

Revision ID: 346be260d9dd
Revises: 007c8695b784
Create Date: 2018-05-05 08:29:59.235293

"""

# revision identifiers, used by Alembic.
revision = '346be260d9dd'
down_revision = '007c8695b784'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim', sa.Column('service_exchange_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim', 'service_exchange_rate')
    # ### end Alembic commands ###
