"""filled out dependent table, dropped has_dependent from insured

Revision ID: 454e9b9a2f52
Revises: c4a7b0cf9edc
Create Date: 2018-03-24 21:32:11.239332

"""

# revision identifiers, used by Alembic.
revision = '454e9b9a2f52'
down_revision = 'c4a7b0cf9edc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dependent', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('dependent', sa.Column('full_time_student', sa.String(length=1), nullable=True))
    op.add_column('dependent', sa.Column('relationship_to_insured', sa.String(length=1), nullable=True))
    op.drop_column('dependent', 'test')
    op.drop_column('insured', 'string_test')
    op.drop_column('insured', 'test')
    op.drop_column('insured', 'has_dependent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insured', sa.Column('has_dependent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('insured', sa.Column('test', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.add_column('insured', sa.Column('string_test', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
    op.add_column('dependent', sa.Column('test', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.drop_column('dependent', 'relationship_to_insured')
    op.drop_column('dependent', 'full_time_student')
    op.drop_column('dependent', 'date_of_birth')
    # ### end Alembic commands ###
