"""testing models.py without BaseModel class

Revision ID: a56c55f1a2eb
Revises: b75bd14df422
Create Date: 2018-02-10 07:49:36.736783

"""

# revision identifiers, used by Alembic.
revision = 'a56c55f1a2eb'
down_revision = 'b75bd14df422'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insured',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insured_email'), 'insured', ['email'], unique=True)
    op.create_index(op.f('ix_insured_username'), 'insured', ['username'], unique=True)
    op.create_table('claim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['insured.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_timestamp'), 'claim', ['timestamp'], unique=False)
    op.drop_table('claims')
    op.drop_table('insureds')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insureds',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('insureds_id_seq'::regclass)"), nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='insureds_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('claims',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['insureds.id'], name='claims_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='claims_pkey')
    )
    op.drop_index(op.f('ix_claim_timestamp'), table_name='claim')
    op.drop_table('claim')
    op.drop_index(op.f('ix_insured_username'), table_name='insured')
    op.drop_index(op.f('ix_insured_email'), table_name='insured')
    op.drop_table('insured')
    # ### end Alembic commands ###
