"""added f diagnosis and service_currency fields to claim

Revision ID: c4a7b0cf9edc
Revises: cff568dd9128
Create Date: 2018-03-13 15:01:04.945150

"""

# revision identifiers, used by Alembic.
revision = 'c4a7b0cf9edc'
down_revision = 'cff568dd9128'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim', sa.Column('diagnosis', sa.String(length=64), nullable=True))
    op.add_column('claim', sa.Column('service_currency', sa.String(length=30), nullable=True))
    op.drop_column('claim', 'service_country')
    op.drop_column('claim', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim', sa.Column('body', sa.VARCHAR(length=140), autoincrement=False, nullable=True))
    op.add_column('claim', sa.Column('service_country', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_column('claim', 'service_currency')
    op.drop_column('claim', 'diagnosis')
    # ### end Alembic commands ###
