"""added fields to claims table

Revision ID: cff568dd9128
Revises: 7d716967a0c2
Create Date: 2018-03-13 14:34:20.876421

"""

# revision identifiers, used by Alembic.
revision = 'cff568dd9128'
down_revision = '7d716967a0c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim', sa.Column('accident_auto', sa.String(length=1), nullable=True))
    op.add_column('claim', sa.Column('accident_date', sa.Date(), nullable=True))
    op.add_column('claim', sa.Column('accident_details', sa.String(length=64), nullable=True))
    op.add_column('claim', sa.Column('accident_employment', sa.String(length=1), nullable=True))
    op.add_column('claim', sa.Column('accident_other', sa.String(length=1), nullable=True))
    op.add_column('claim', sa.Column('service_amount', sa.Float(), nullable=True))
    op.add_column('claim', sa.Column('service_country', sa.String(length=30), nullable=True))
    op.add_column('claim', sa.Column('service_date', sa.Date(), nullable=True))
    op.add_column('claim', sa.Column('service_details', sa.String(length=64), nullable=True))
    op.add_column('claim', sa.Column('service_provider', sa.String(length=30), nullable=True))
    op.add_column('claim', sa.Column('service_type', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim', 'service_type')
    op.drop_column('claim', 'service_provider')
    op.drop_column('claim', 'service_details')
    op.drop_column('claim', 'service_date')
    op.drop_column('claim', 'service_country')
    op.drop_column('claim', 'service_amount')
    op.drop_column('claim', 'accident_other')
    op.drop_column('claim', 'accident_employment')
    op.drop_column('claim', 'accident_details')
    op.drop_column('claim', 'accident_date')
    op.drop_column('claim', 'accident_auto')
    # ### end Alembic commands ###
