"""empty message

Revision ID: 566cb089a510
Revises: 4cb7113f8459
Create Date: 2018-02-08 07:57:41.789495

"""

# revision identifiers, used by Alembic.
revision = '566cb089a510'
down_revision = '4cb7113f8459'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insureds', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.add_column('insureds', sa.Column('username', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_insureds_email'), 'insureds', ['email'], unique=True)
    op.create_index(op.f('ix_insureds_username'), 'insureds', ['username'], unique=True)
    op.drop_column('insureds', 'last_name')
    op.drop_column('insureds', 'password')
    op.drop_column('insureds', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insureds', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('insureds', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('insureds', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_insureds_username'), table_name='insureds')
    op.drop_index(op.f('ix_insureds_email'), table_name='insureds')
    op.drop_column('insureds', 'username')
    op.drop_column('insureds', 'password_hash')
    # ### end Alembic commands ###
