"""secommented out Dependent class/table

Revision ID: 980c9a28bad1
Revises: 7546e1c647c5
Create Date: 2018-02-23 08:01:44.921740

"""

# revision identifiers, used by Alembic.
revision = '980c9a28bad1'
down_revision = '7546e1c647c5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dependent')
    op.drop_constraint('claim_dependent_id_fkey', 'claim', type_='foreignkey')
    op.drop_column('claim', 'dependent_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim', sa.Column('dependent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('claim_dependent_id_fkey', 'claim', 'dependent', ['dependent_id'], ['id'])
    op.create_table('dependent',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('insured_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('middle_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('relationship_to_insured', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['insured_id'], ['insured.id'], name='dependent_insured_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='dependent_pkey')
    )
    # ### end Alembic commands ###
