"""added last seen to insured model

Revision ID: fdcd108f5bc0
Revises: a56c55f1a2eb
Create Date: 2018-02-16 07:34:58.967263

"""

# revision identifiers, used by Alembic.
revision = 'fdcd108f5bc0'
down_revision = 'a56c55f1a2eb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insured', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insured', 'last_seen')
    # ### end Alembic commands ###
