"""foreign key in dependent table takes 'insured.id' and is not nullable

Revision ID: 16e37c9af107
Revises: 58ac001d66bd
Create Date: 2018-02-28 07:37:41.149826

"""

# revision identifiers, used by Alembic.
revision = '16e37c9af107'
down_revision = '58ac001d66bd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dependent', 'insured_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dependent', 'insured_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
