"""chadded gender column (string) back into insured table

Revision ID: 1a796f2480f9
Revises: 20ff6340bdd1
Create Date: 2018-02-24 12:18:24.715183

"""

# revision identifiers, used by Alembic.
revision = '1a796f2480f9'
down_revision = '20ff6340bdd1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insured', sa.Column('gender', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insured', 'gender')
    # ### end Alembic commands ###
