"""chremoved gender column from insured table for now

Revision ID: 20ff6340bdd1
Revises: e575f5fa1930
Create Date: 2018-02-24 12:09:37.128395

"""

# revision identifiers, used by Alembic.
revision = '20ff6340bdd1'
down_revision = 'e575f5fa1930'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insured', 'gender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insured', sa.Column('gender', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
