"""dropped alembic_version table from db, deleted migrations dir, re-ran init

Revision ID: 27ec081ae453
Revises: None
Create Date: 2018-02-24 09:09:50.437048

"""

# revision identifiers, used by Alembic.
revision = '27ec081ae453'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim', 'dependent_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim', sa.Column('dependent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
