"""minor changes to virtual fields (claims) in insured and dependent tables

Revision ID: 46e3d310b404
Revises: e40b54edc6a1
Create Date: 2018-03-01 07:12:19.150090

"""

# revision identifiers, used by Alembic.
revision = '46e3d310b404'
down_revision = 'e40b54edc6a1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dependent', 'insured_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dependent', 'insured_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
