"""add has_dependent column to insured table

Revision ID: 58ac001d66bd
Revises: edded0e305b8
Create Date: 2018-02-27 07:00:04.711188

"""

# revision identifiers, used by Alembic.
revision = '58ac001d66bd'
down_revision = 'edded0e305b8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insured', sa.Column('has_dependent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insured', 'has_dependent')
    # ### end Alembic commands ###
