"""readded dependent table

Revision ID: 79d1c1e8122c
Revises: 90929c9c7dc9
Create Date: 2018-02-25 21:58:55.879841

"""

# revision identifiers, used by Alembic.
revision = '79d1c1e8122c'
down_revision = '90929c9c7dc9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('middle_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('test', sa.String(length=15), nullable=True),
    sa.Column('gender', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dependent')
    # ### end Alembic commands ###
