"""readded test and gender columns to insured table

Revision ID: 90929c9c7dc9
Revises: 0cf1eb3544e1
Create Date: 2018-02-25 21:22:53.394584

"""

# revision identifiers, used by Alembic.
revision = '90929c9c7dc9'
down_revision = '0cf1eb3544e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insured', sa.Column('gender', sa.String(length=15), nullable=True))
    op.add_column('insured', sa.Column('test', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insured', 'test')
    op.drop_column('insured', 'gender')
    # ### end Alembic commands ###
