"""readded dependent table with foreign key for insured table

Revision ID: ab4c0292cf3c
Revises: 79d1c1e8122c
Create Date: 2018-02-25 22:00:52.256921

"""

# revision identifiers, used by Alembic.
revision = 'ab4c0292cf3c'
down_revision = '79d1c1e8122c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dependent', sa.Column('insured_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dependent', 'insured', ['insured_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dependent', type_='foreignkey')
    op.drop_column('dependent', 'insured_id')
    # ### end Alembic commands ###
