"""foallowed insured_id column (foreign key) of dependent table to be nullable

Revision ID: e40b54edc6a1
Revises: 16e37c9af107
Create Date: 2018-02-28 08:19:17.849374

"""

# revision identifiers, used by Alembic.
revision = 'e40b54edc6a1'
down_revision = '16e37c9af107'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dependent', 'insured_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dependent', 'insured_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
