"""readded dependent table with foreign key in claims for dependent table

Revision ID: edded0e305b8
Revises: ab4c0292cf3c
Create Date: 2018-02-25 22:06:40.522541

"""

# revision identifiers, used by Alembic.
revision = 'edded0e305b8'
down_revision = 'ab4c0292cf3c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim', sa.Column('dependent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'claim', 'dependent', ['dependent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'claim', type_='foreignkey')
    op.drop_column('claim', 'dependent_id')
    # ### end Alembic commands ###
