"""addeded dob and air_id to Insured

Revision ID: 292ab5979b98
Revises: 38f583af10c8
Create Date: 2018-03-10 10:24:57.196509

"""

# revision identifiers, used by Alembic.
revision = '292ab5979b98'
down_revision = '38f583af10c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insured', sa.Column('air_id', sa.String(length=20), nullable=True))
    op.add_column('insured', sa.Column('date_of_birth', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insured', 'date_of_birth')
    op.drop_column('insured', 'air_id')
    # ### end Alembic commands ###
