"""testing string column in place of boolean

Revision ID: 6e65688ccb85
Revises: 431d5cd12fd7
Create Date: 2018-03-10 13:02:41.506837

"""

# revision identifiers, used by Alembic.
revision = '6e65688ccb85'
down_revision = '431d5cd12fd7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insured', sa.Column('string_test', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insured', 'string_test')
    # ### end Alembic commands ###
