"""updating boolean data types to string in Insured

Revision ID: b1f523801621
Revises: 6e65688ccb85
Create Date: 2018-03-10 13:38:09.250782

"""

# revision identifiers, used by Alembic.
revision = 'b1f523801621'
down_revision = '6e65688ccb85'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('insured', 'full_time_student',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=1),
               existing_nullable=True)
    op.alter_column('insured', 'gender',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=1),
               existing_nullable=True)
    op.alter_column('insured', 'medicare_part_a',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=1),
               existing_nullable=True)
    op.alter_column('insured', 'medicare_part_b',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=1),
               existing_nullable=True)
    op.alter_column('insured', 'other_coverage',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=1),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('insured', 'other_coverage',
               existing_type=sa.String(length=1),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.alter_column('insured', 'medicare_part_b',
               existing_type=sa.String(length=1),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.alter_column('insured', 'medicare_part_a',
               existing_type=sa.String(length=1),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.alter_column('insured', 'gender',
               existing_type=sa.String(length=1),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    op.alter_column('insured', 'full_time_student',
               existing_type=sa.String(length=1),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    # ### end Alembic commands ###
